# Generated by Django 5.0 on 2023-12-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_infoprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoprod',
            name='modelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.producto'),
        ),
    ]
