# Generated by Django 5.0 on 2023-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_infoprod_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoprod',
            name='imagen',
            field=models.FileField(upload_to='media/producto'),
        ),
    ]
