# Generated by Django 5.0 on 2023-12-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_infoprod_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoprod',
            name='imagen',
            field=models.FileField(upload_to='productos'),
        ),
    ]
