# Generated by Django 5.0 on 2023-12-16 19:04

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', base.models.UpperField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=2000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', base.models.UpperField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cuerpo', models.TextField()),
                ('imagen', models.FileField(upload_to='posts')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
        ),
    ]
