# Generated by Django 5.0 on 2023-12-17 21:15

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_blog_titulo_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=base.models.UpperField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=base.models.UpperField(max_length=100),
        ),
    ]
