# Generated by Django 4.2.6 on 2023-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
