# Generated by Django 4.2.6 on 2023-11-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_producto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
    ]
