# Generated by Django 4.2.6 on 2023-11-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_compras_dir_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefono',
        ),
    ]
