# Generated by Django 5.0 on 2023-12-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, unique=True)),
                ('producto', models.CharField(max_length=100)),
                ('categoria', models.IntegerField(choices=[(1, 'Línea Blanca'), (2, 'Electrodoméstico'), (3, 'Informática')])),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')])),
            ],
        ),
    ]
