# Generated by Django 5.0 on 2023-12-12 01:42

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=base.models.UpperField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=base.models.UpperField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=base.models.UpperField(max_length=100),
        ),
    ]
