# Generated by Django 5.0 on 2023-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_producto_marca_alter_producto_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Línea Blanca'), (2, 'Electro'), (3, 'Informática')]),
        ),
    ]
