# Generated by Django 5.0 on 2023-12-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_producto_stock_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to='PRODUCTO')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto', unique=True)),
            ],
        ),
    ]
