# Generated by Django 5.0 on 2023-12-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_blog_post_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(),
        ),
    ]
