# Generated by Django 5.0 on 2023-12-18 03:54

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_blog_autor_alter_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=base.models.UpperField(max_length=100, unique=True),
        ),
    ]
