# Generated by Django 5.0 on 2023-12-18 04:21

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_post_blog_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=base.models.UpperField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=base.models.UpperField(max_length=100),
        ),
    ]
